"""Added education_days and education_tasks

Revision ID: f97e57bc1470
Revises: 39a5042bd099
Create Date: 2021-10-02 22:33:43.315886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97e57bc1470'
down_revision = '39a5042bd099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_days',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('education_day_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['education_day_id'], ['education_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education_tasks')
    op.drop_table('education_days')
    # ### end Alembic commands ###
